name: Check
on:
  push:
    branches:
      - main
  pull_request:
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.38.0
      - uses: actions/cache@v3
        with:
          path: |
            ~/.deno
            ~/.cache/deno
          key: ${{ runner.os }}-deno-${{ hashFiles('import-map.json') }}
      - name: Checkout
        uses: actions/checkout@v4
      - name: Lint
        run: deno task lint
      - name: Test
        run: deno task test

